[package]
name = "lefis-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "3.3.2" }
futures = "0.3.18"
pretty_env_logger = "0.4.0" 
log = "0.4"
lazy_static = "*"
serde = "1"
serde_derive = "1"
serde_json = "1"
regex = "1"
flate2 = "1"
base64 = "0.13.0"
